local-phone-apps = Apollo \                 
                   ApplicationsProvider \                 
                   BackupRestoreConfirmation \                 
                   BasicDreams \                 
                   Bluetooth \                 
                   Browser \                 
                   Calculator \                 
                   Calendar \                 
                   CalendarProvider \                 
                   CellBroadcastReceiver \                 
                   CertInstaller \                 
                   Contacts \                 
                   ContactsProvider \                 
                   DefaultContainerService \                 
                   DeskClock \                 
                   Development \                 
                   DownloadProvider \                 
                   DownloadProviderUi \                 
                   DrmProvider \                 
                   DSPManager \                 
                   Email2 \                 
                   Exchange2 \                 
                   FusedLocation \                 
                   Galaxy4 \                 
                   Gallery2 \                 
                   GooglePinyinIME \                 
                   HoloSpiralWallpaper \                 
                   HTMLViewer \                 
                   InputDevices \                 
                   KeyChain \                 
                   LiveWallpapers \                 
                   LiveWallpapersPicker \                 
                   LockClock \                 
                   MagicSmokeWallpapers \                 
                   MediaProvider \                 
                   Mms \                 
                   NoiseField \                 
                   PackageInstaller \                 
                   PhaseBeam \                 
                   Phone \                 
                   PhotoTable \                 
                   PicoTts \                 
                   Provision \                 
                   QuickSearchBox \                 
                   RootExplorer \                 
                   Settings \                 
                   SettingsProvider \                 
                   SharedStorageBackup \                 
                   SoundRecorder \                 
                   Stk \                 
                   Sweep2Wake \                 
                   SystemUI \                 
                   TelephonyProvider \                 
                   Term \                 
                   ThemeChooser \                 
                   ThemeManager \                 
                   Torch \                 
                   Trebuchet \                 
                   UserDictionaryProvider \                 
                   VisualizationWallpapers \                 
                   VoicePlus \                 
                   VpnDialogs \                 
                   WAPPushManager \                 
